### ISSUE TITLE
please help me out

### ISSUE THREAD

**Issue by dineshkumar99999** [dallmann-consulting/OCPP.Core#10]
Hello I have created charge points and server page using ocpp.core.server and ocpp.core.management. Using OCPP1.6 simulator I can able to connect, start, stop charging. But now my intention is Schedule charging. From ocpp2.0 simulator when I am giving start,stop,schedule it shows JSON  is not accepted.
![OCPP2 0](https://user-images.githubusercontent.com/100535258/159207960-0ba0e6f9-0041-45f3-9ad5-4e013b1647b3.png)

please help me out to solve my doubts

**Comment by dallmann-consulting** [comment]
Hi,
it is my understanding that the OCPP backend can send a schedule to the charging station. 
Are you trying to send a schedule from the charging station (=simulator) to the server? The OCPP messages don't allow that and it doesn't seem to make sense to me because the charging station is the one to adhere to the schedule. Is this a misunderstanding?
Can you attach the exakt message you are sending?

**Comment by dineshkumar99999** [comment]
Yes OCPP backend can send a schedule to the charging station. I am also trying the same. But it is not working. when I click on Notify EV charging Schedule on cp20 simulator it is not working

**Comment by dallmann-consulting** [comment]
You mean the "Notify EV Charging Schedule", correct? This works for me:

![image](https://user-images.githubusercontent.com/51120629/160256758-574aea07-0984-491a-bca4-3f9047fa146e.png)


The simulator sends a 'NotifyEVChargingSchedule'  message and the OCPP server answers with status=accepted.
Are you using the simulators included in this project?

**Comment by dineshkumar99999** [comment]
Yes I am using the simulators which is included in this project. Then why it is not working for me?

**Comment by dallmann-consulting** [comment]
Sorry - without further details (ocpp messages and log) I cannot help you.

**Comment by dallmann-consulting** [comment]
No further activity... close thread.
