### ISSUE TITLE
API 

### ISSUE THREAD

**Issue by vasya00044** [dallmann-consulting/OCPP.Core#5]
Hi. Installed. Great program. Is there an OCPP API for the server? I want to make an application with a payment system for payment on time and payment for kW.

**Comment by dallmann-consulting** [comment]
Hi, the server basically writes all relevant information in the database. You can read it from there.
There is a simple REST-API for getting status information (which charge points are connected) and some charge point actions (like initiating a reboot).
Payment can be difficult because you need to rely on the messages from the charge points. In case of connectivity problems it is valid that the charge points store the messages and send them later. So there is no guarantee that the OCPP server has exact and live data.
