### ISSUE TITLE
No current status could be retrieved from the OCPP server

### ISSUE THREAD

**Issue by WELIZARY** [dallmann-consulting/OCPP.Core#54]
The charging stations work and are displayed correctly, but this error is always lit at the bottom

![Screenshot_20240423-074914~2.png](https://github.com/dallmann-consulting/OCPP.Core/assets/136910679/885e7791-7c76-4182-b8e1-91e92cf2494f)

The following error appears in the server log
![IMG-4d3e9d385f8585f1167587e769e3c99d-V.jpg](https://github.com/dallmann-consulting/OCPP.Core/assets/136910679/e2aa237b-f371-4446-80b7-4b2a339fda1e)

How can I display data on the charge level and power consumption like in your screenshots?  This information is in the logs, but is not displayed on the dashboard

![IMG-213fd582f79646943936618d69b5d4ff-V.jpg](https://github.com/dallmann-consulting/OCPP.Core/assets/136910679/ed5b73a3-57dd-45fe-8b3b-93710573c453)

![IMG-63206c76bbc1daedfa844cf40db1fd89-V.jpg](https://github.com/dallmann-consulting/OCPP.Core/assets/136910679/912bd274-d007-447f-baa3-aa4419345ee4)

**Comment by JeremyMahieu** [comment]
Probably the database queries are starting to take too long (longer than 4s) due to slow database views and lack of indexes. I fixed this in [this pull request](https://github.com/dallmann-consulting/OCPP.Core/pull/53), give it a try. 

You can use [this fork](https://github.com/JeremyMahieu/OCPP.Core) where a few of these pull requests are already merged with the main.

**Comment by dallmann-consulting** [comment]
The Web-UI contacts the server to get the connection status of all charge points and connectors. The appsettings.json contains the URL and a secret key (see the matching key in the server settings ) for this status request:

```
  "ServerApiUrl": "http://localhost:8081/API",
  "ApiKey": "36029A5F-B736-4DA9-AE46-D66847C9062C",
```

If this request fails you get the above error message. 


Regarding the charging information shown:
Usual home chargers are only sending updated meter valued periodically. They don't send a SoC and the don't send power values. The Web-UI currently only shows the elapsed time, since the transaction startet (the tile is red). When the transaction has stopped (the tile is green) it shows the charged amount (kWh) of the last transaction. That is what you see in the screenshot.
If you are using the included modified chargepoint simulator you can also send a SoC and that gets displayed. But home chargers ususally don't send this information.
I already had the idea to also show the charged amount (until the latest transmitted meter value) in the active status (red tile) and the charging power could be calculated from the time between the last two meter values. But is this really interesting for a home charger with limited power? Most people just plug in their cars at home or work and the car charges itself to a certain determined level. It didn't seem very useful to me.

**Comment by dallmann-consulting** [comment]
Yes, but if you look at the messages every minute you will probably see that they only contain updated meter values. This is currently not displayed (as stated above) because it doesn't seem very usefull with slow chargers. If I want to see the progress I check the SoC in my car and not the currently charged kWh.

**Comment by dallmann-consulting** [comment]
Sorry, my request goes to JeremyMahieu.
