### ISSUE TITLE
StartTransaction.req

### ISSUE THREAD

**Issue by FuYan** [dallmann-consulting/OCPP.Core#76]
![image](https://github.com/user-attachments/assets/06f286cb-c816-4067-93c3-c51982038f3e)
![image](https://github.com/user-attachments/assets/7d2c6fcc-f54f-4c94-b1bf-fe3d5ab19324)

ocpp1.6文档写的是此参数可选，代码执行的是必填，导致开始充电错误
The OCPP1.6 document states that this parameter is optional, but the code execution is mandatory, resulting in an error in starting charging

**Comment by dallmann-consulting** [comment]
Well yes and no. The field itself is optional. You can omit that. 
But **IF** your json contains a reservationId it must have a valid integer value. Otherwise it would be "null" which is not allowed.
In your first screenshot you can see that the connectorId is required. It is marked with "Json.Required.Always". The reservationId doesn't have that.
It is an optional field but it needs a proper integer value.
